---@diagnostic disable: undefined-global
--# selene: allow(undefined_variable)
-- Run :Lushify
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local snazzy = require("lush_theme.snazzy.palette").dark
local theme = lush(function(injected_functions)
	---@type function
	local sym = injected_functions.sym
	return {
		Boolean { fg = snazzy.magenta },
		Character { fg = "#e2e4e5" },
		ColorColumn { sp = snazzy.statusline.bg, bg = "#3a3d4d" },
		Comment { gui = "italic", fg = "#606580" },
		Conceal { fg = "#686868" },
		Conditional { fg = snazzy.yellow },
		Constant { fg = snazzy.yellow },
		Debug { fg = snazzy.yellow },
		Define { fg = snazzy.purple },
		Identifier { fg = snazzy.cyan },
		IncSearch { bg = snazzy.search, fg = snazzy.bg },
		Macro { fg = snazzy.purple },
		NonText { fg = "#606580" },
		Normal {
			fg = snazzy.fg,
			bg = snazzy.normal_bg,
		},
		NormalFloat { fg = "#eff0eb" },
		Operator { fg = snazzy.magenta },
		Pmenu { sp = snazzy.statusline.bg, fg = snazzy.base8 },
		PmenuSbar { sp = "#686868", bg = "#686868", fg = "#f9f9f9" },
		PmenuSel { sp = snazzy.statusline.bg, bg = "#3a3d4d" },
		PmenuSelBold { sp = snazzy.statusline.bg, fg = snazzy.green, bg = "#3a3d4d", gui = "bold" },
		PmenuThumb { bg = snazzy.overlay },
		PreCondit { fg = snazzy.yellow },
		PreProc { fg = snazzy.red },
		Search { bg = snazzy.search, fg = snazzy.bg },
		Special { fg = snazzy.cyan },
		SpecialChar { fg = snazzy.pink },
		SpecialComment { fg = snazzy.purple },
		SpecialKey { gui = "italic", fg = "#5e6c70" },
		Statement { fg = snazzy.magenta },
		StatusLine { sp = snazzy.statusline.bg, bg = "#3a3d4d", fg = "#eff0eb" },
		StatusLineNC { sp = snazzy.statusline.bg, bg = "#3a3d4d", fg = "#a1a6a8" },
		StorageClass { fg = snazzy.blue },
		String { fg = snazzy.green },
		Structure { fg = snazzy.yellow },
		Substitute { bg = snazzy.pink, fg = snazzy.bg },
		TermCursor { gui = "reverse" },
		Terminal { fg = "#eff0eb" },
		Title { fg = snazzy.yellow },
		Todo { gui = "italic", fg = snazzy.yellow },
		Type { fg = snazzy.cyan },
		Typedef { Structure },
		Underlined { sp = "#f1f1f0", gui = "underline", fg = "#f9f9ff" },
		VertSplit { bg = "#282a36", fg = "#606580" },
		-- Visual { sp = snazzy.ui_7, bg = snazzy.ui_7 },
		-- VisualNOS { sp = snazzy.ui_7, bg = snazzy.ui_7 },
		Visual { bg = "#3a3d4d" },
		VisualNOS { bg = "#3a3d4d" },
		WarningMsg { fg = snazzy.orange },
		Whitespace { fg = "#3f444a" },
		WildMenu { sp = "#a1a6a8", bg = "#a1a6a8" },
		WinBar { gui = "bold" },
		WinBarNC { WinBar },
		WinSeparator { VertSplit },

		-- Treesitter highlights
		TSCurrentNode { bg = "#303340" },
		TSCurrentScope { bg = snazzy.statusline.bg },
		TSParameterReference { fg = snazzy.yellow },
		TSQueryLinterError { fg = snazzy.red },

		sym("@none") {},

		sym("@annotation") { fg = snazzy.blue },
		sym("@attribute") { fg = snazzy.blue },
		sym("@boolean") { fg = snazzy.purple },
		sym("@character") { fg = snazzy.pink },
		sym("@character.special") { SpecialChar },
		sym("@comment") { gui = "italic", fg = "#606580" },
		sym("@comment.danger") { fg = snazzy.orange },
		sym("@comment.note") { SpecialComment },
		sym("@comment.todo") { fg = snazzy.cyan },
		sym("@comment.warning") { fg = snazzy.orange },
		sym("@constant") { fg = snazzy.yellow },
		sym("@constant.builtin") { fg = snazzy.yellow },
		sym("@constant.macro") { fg = snazzy.orange },
		sym("@constructor") { fg = snazzy.blue },
		sym("@definition") { sp = snazzy.statusline.bg, bg = "#3a3d4d" },
		sym("@definition.usage") { sp = snazzy.statusline.bg, bg = "#3a3d4d" },
		sym("@diff.delta") { fg = snazzy.diff.change },
		sym("@diff.minus") { fg = snazzy.diff.delete },
		sym("@diff.plus") { fg = snazzy.diff.add },
		sym("@error") { fg = snazzy.red },
		sym("@function") { fg = snazzy.blue },
		sym("@function.builtin") { fg = snazzy.yellow },
		sym("@function.call") { fg = snazzy.blue },
		sym("@function.macro") { fg = snazzy.blue },
		sym("@function.method") { fg = snazzy.blue },
		sym("@function.method.call") { fg = snazzy.blue },
		sym("@include") { fg = snazzy.magenta },
		sym("@keyword") { fg = snazzy.magenta },
		sym("@keyword.conditional") { fg = snazzy.magenta },
		sym("@keyword.coroutine") { fg = snazzy.magenta },
		sym("@keyword.debug") { fg = snazzy.yellow },
		sym("@keyword.directive") { fg = snazzy.red },
		sym("@keyword.directive.define") { fg = snazzy.purple },
		sym("@keyword.exception") { fg = snazzy.red },
		sym("@keyword.function") { fg = snazzy.red },
		sym("@keyword.import") { fg = snazzy.yellow },
		sym("@keyword.operator") { fg = snazzy.magenta },
		sym("@keyword.repeat") { fg = snazzy.magenta },
		sym("@keyword.return") { fg = snazzy.red },
		sym("@keyword.storage") { fg = snazzy.magenta },
		sym("@keyword.modifier") { fg = snazzy.red },
		sym("@keyword.type") { fg = snazzy.magenta },
		sym("@label") { fg = snazzy.pink },
		sym("@markup.emphasis") { gui = "italic" },
		sym("@markup.environment") { Macro },
		sym("@markup.environment.name") { Type },
		sym("@markup.heading") { Title },
		sym("@markup.link") { Constant },
		sym("@markup.link.label") { SpecialChar },
		sym("@markup.link.uri") { gui = "underline", fg = snazzy.blue },
		sym("@markup.list") { fg = snazzy.yellow },
		sym("@markup.math") { Special },
		sym("@markup.raw") { sym("@none") },
		sym("@markup.strike") { gui = "strikethrough" },
		sym("@markup.strong") { gui = "bold" },
		sym("@markup.underline") { gui = "underline" },
		sym("@module") { fg = snazzy.cyan },
		sym("@number") { fg = snazzy.orange },
		sym("@number.float") { fg = "#a1a6a8" },
		sym("@operator") { fg = snazzy.pink },
		sym("@property") { Identifier },
		sym("@punctuation.bracket") { fg = snazzy.base6 },
		sym("@punctuation.delimiter") { fg = snazzy.base7 },
		sym("@string") { fg = snazzy.green },
		sym("@string.escape") { fg = snazzy.pink },
		sym("@string.regexp") { String },
		sym("@string.special.symbol") { fg = snazzy.green },
		sym("@string.special.url") { gui = "underline", fg = snazzy.blue },
		sym("@structure") { fg = snazzy.orange },
		sym("@tag") { fg = snazzy.cyan },
		sym("@tag.attribute") { fg = snazzy.yellow },
		sym("@tag.delimiter") { fg = snazzy.magenta },
		sym("@type") { fg = snazzy.yellow },
		sym("@type.builtin") { fg = snazzy.yellow },
		sym("@type.definition") { Typedef },
		sym("@type.qualifier") { Type },
		sym("@variable") { fg = "#eff0eb" },
		sym("@variable.builtin") { fg = snazzy.pink },
		sym("@variable.member") { fg = snazzy.cyan },
		sym("@variable.parameter") { fg = snazzy.base9 },
		sym("@lsp.type.string") { sym("@none") },
		sym("@namespace.builtin") { fg = snazzy.pink },

		-- LSP highlights
		sym("@lsp.type.class") { Structure },
		sym("@lsp.type.comment") { Comment },
		sym("@lsp.type.decorator") { sym("@function") },
		sym("@lsp.type.enum") { Structure },
		sym("@lsp.type.enumMember") { Constant },
		sym("@lsp.type.function") { sym("@function") },
		sym("@lsp.type.interface") { Structure },
		sym("@lsp.type.macro") { Macro },
		sym("@lsp.type.method") { sym("@function.method") },
		sym("@lsp.type.namespace") { sym("@module") },
		sym("@lsp.type.parameter") { sym("@variable.parameter") },
		sym("@lsp.type.property") { sym("@property") },
		sym("@lsp.type.struct") { Structure },
		sym("@lsp.type.type") { sym("@type") },
		sym("@lsp.type.typeParameter") { Typedef },
		sym("@lsp.type.variable") {},
		sym("@lsp.type.variable.go") { sym("@lsp.type.variable") },
		sym("@lsp.type.keyword") { sym("@none") },

		sym("@lsp.mod.global.lua") { fg = snazzy.yellow },
		sym("@lsp.typemod.function.defaultLibrary.lua") { fg = snazzy.yellow },
		sym("@lsp.typemod.class.constructorOrDestructor") { fg = snazzy.blue },
		sym("@lsp.mod.constructorOrDestructor") { fg = snazzy.blue },
		sym("@lsp.typemod.variable.macro.rust") { fg = snazzy.green },
		sym("@lsp.typemod.variable.readonly") { Define },
		sym("@lsp.typemod.function.global") { fg = snazzy.blue },
		sym("@markup.raw.block.vimdoc") { String },
		sym("@markup.raw.markdown_inline") { bg = "#3a3d4d" },

		DiagnosticDefaultError { fg = snazzy.red },
		DiagnosticDefaultHint { fg = snazzy.green },
		DiagnosticDefaultInfo { fg = snazzy.cyan },
		DiagnosticDefaultWarn { fg = snazzy.yellow },
		DiagnosticError { fg = snazzy.red },
		DiagnosticFloatingError { fg = snazzy.red },
		DiagnosticFloatingHint { fg = snazzy.green },
		DiagnosticFloatingInfo { fg = snazzy.cyan },
		DiagnosticFloatingWarn { fg = snazzy.yellow },
		DiagnosticHint { fg = snazzy.green },
		DiagnosticInfo { fg = snazzy.cyan },
		DiagnosticSignError { fg = snazzy.red },
		DiagnosticSignHint { fg = snazzy.green },
		DiagnosticSignInfo { fg = snazzy.cyan },
		DiagnosticSignWarn { fg = snazzy.yellow },
		DiagnosticUnderlineError { sp = snazzy.red, gui = "underline", fg = "#ff5c57" },
		DiagnosticUnderlineHint { sp = snazzy.green, gui = "underline" },
		DiagnosticUnderlineInfo { sp = snazzy.blue, gui = "underline" },
		DiagnosticUnderlineWarn { sp = snazzy.yellow, gui = "underline" },
		DiagnosticVirtualTextError { fg = snazzy.red },
		DiagnosticVirtualTextHint { fg = snazzy.green },
		DiagnosticVirtualTextInfo { fg = snazzy.cyan },
		DiagnosticVirtualTextWarn { fg = snazzy.yellow },
		DiagnosticWarn { fg = snazzy.yellow },

		NvimInternalError { bg = snazzy.red, fg = "#ff5c57" },

		CopilotSuggestion { bg = "#303340", fg = snazzy.blue },
		Cursor { gui = "reverse" },
		CursorColumn { sp = snazzy.statusline.bg, bg = "#3a3d4d", fg = "#e2e4e5" },
		CursorLine { bg = snazzy.cursorline },
		CursorLineFold { bg = "#303340", gui = "italic", fg = snazzy.blue },
		CursorLineNr { bg = "#303340", fg = snazzy.yellow },
		CursorLineSign { bg = "#303340" },
		CursorWord0 { bg = "#686868" },
		CursorWord1 { bg = snazzy.green },
		DashboardCenter { fg = snazzy.blue },
		DashboardFooter { fg = "#686868" },
		DashboardHeader { fg = snazzy.yellow },
		DashboardShortCut { fg = snazzy.magenta },
		diffRemoved { fg = snazzy.red },
		diffAdded { fg = snazzy.green },
		diffChanged { fg = snazzy.blue },
		diffFile { fg = snazzy.cyan },
		diffIndexLine { fg = snazzy.magenta },
		diffLine { fg = "#686868" },
		diffNewFile { fg = snazzy.yellow },
		diffOldFile { fg = snazzy.yellow },
		DefxIconsParentDirectory { fg = snazzy.yellow },
		Defx_filename_directory { fg = snazzy.blue },
		Defx_filename_root { fg = snazzy.red },
		Delimiter { fg = snazzy.yellow },
		DevIconAi { fg = "#cbcb41" },
		DevIconAwk { fg = "#4d5a5e" },
		DevIconBabelrc { fg = "#cbcb41" },
		DevIconBash { fg = "#89e051" },
		DevIconBashProfile { fg = "#89e051" },
		DevIconBashrc { fg = "#89e051" },
		DevIconBat { fg = "#c1f12e" },
		DevIconBinaryGLTF { fg = "#ffb13b" },
		DevIconBmp { fg = "#a074c4" },
		DevIconBrewfile { fg = "#701516" },
		DevIconC { fg = snazzy.cyan },
		DevIconCMake { fg = "#6d8086" },
		DevIconCMakeLists { fg = "#6d8086" },
		DevIconCPlusPlus { fg = snazzy.magenta },
		DevIconClojure { fg = "#8dc149" },
		DevIconClojureC { fg = "#8dc149" },
		DevIconClojureDart { fg = "#519aba" },
		DevIconClojureJS { fg = "#519aba" },
		DevIconCobol { fg = "#005ca5" },
		DevIconCoffee { fg = "#cbcb41" },
		DevIconConf { fg = "#6d8086" },
		DevIconConfigRu { fg = "#701516" },
		DevIconConfiguration { fg = "#ececec" },
		DevIconCp { fg = "#519aba" },
		DevIconCpp { fg = "#519aba" },
		DevIconCrystal { fg = "#000000" },
		DevIconCs { fg = "#596706" },
		DevIconCsh { fg = "#4d5a5e" },
		DevIconCson { fg = "#cbcb41" },
		DevIconCss { fg = "#42a5f5" },
		DevIconCsv { fg = "#89e051" },
		DevIconCxx { fg = "#519aba" },
		DevIconD { fg = "#427819" },
		DevIconDart { fg = "#03589c" },
		DevIconDb { fg = "#dad8d8" },
		DevIconDefault { fg = "#6d8086" },
		DevIconDesktopEntry { fg = "#563d7c" },
		DevIconDiff { fg = "#41535b" },
		DevIconDoc { fg = "#185abd" },
		DevIconDockerfile { fg = "#384d54" },
		DevIconDrools { fg = "#ffafaf" },
		DevIconDropbox { fg = "#0061fe" },
		DevIconDsStore { fg = "#41535b" },
		DevIconDump { fg = "#dad8d8" },
		DevIconEdn { fg = "#519aba" },
		DevIconEex { fg = "#a074c4" },
		DevIconEjs { fg = "#cbcb41" },
		DevIconElm { fg = "#519aba" },
		DevIconEnv { fg = "#faf743" },
		DevIconEpp { fg = "#ffa61a" },
		DevIconErb { fg = "#701516" },
		DevIconErl { fg = "#b83998" },
		DevIconEx { fg = "#a074c4" },
		DevIconExs { fg = "#a074c4" },
		DevIconFavicon { fg = "#cbcb41" },
		DevIconFennel { fg = "#fff3d7" },
		DevIconFish { fg = "#4d5a5e" },
		DevIconFs { fg = "#519aba" },
		DevIconFsharp { fg = "#519aba" },
		DevIconFsi { fg = "#519aba" },
		DevIconFsscript { fg = "#519aba" },
		DevIconFsx { fg = "#519aba" },
		DevIconGDScript { fg = "#6d8086" },
		DevIconGemfile { fg = snazzy.red },
		DevIconGemspec { fg = "#701516" },
		DevIconGif { fg = "#a074c4" },
		DevIconGitAttributes { fg = "#41535b" },
		DevIconGitCommit { fg = "#41535b" },
		DevIconGitConfig { fg = "#41535b" },
		DevIconGitIgnore { fg = "#41535b" },
		DevIconGitLogo { fg = "#f14c28" },
		DevIconGitModules { fg = "#41535b" },
		DevIconGitlabCI { fg = "#e24329" },
		DevIconGo { fg = snazzy.cyan },
		DevIconGodotProject { fg = "#6d8086" },
		DevIconGruntfile { fg = "#e37933" },
		DevIconGulpfile { fg = "#cc3e44" },
		DevIconGvimrc { fg = snazzy.green },
		DevIconH { fg = "#a074c4" },
		DevIconHaml { fg = "#eaeae1" },
		DevIconHbs { fg = "#f0772b" },
		DevIconHeex { fg = "#a074c4" },
		DevIconHh { fg = "#a074c4" },
		DevIconHpp { fg = "#a074c4" },
		DevIconHrl { fg = "#b83998" },
		DevIconHs { fg = "#a074c4" },
		DevIconHtm { fg = "#e34c26" },
		DevIconHtml { fg = "#e44d26" },
		DevIconHxx { fg = "#a074c4" },
		DevIconIco { fg = "#cbcb41" },
		DevIconImportConfiguration { fg = "#ececec" },
		DevIconIni { fg = "#6d8086" },
		DevIconJava { fg = "#cc3e44" },
		DevIconJl { fg = "#a270ba" },
		DevIconJpeg { fg = "#a074c4" },
		DevIconJpg { fg = "#a074c4" },
		DevIconJs { fg = snazzy.yellow },
		DevIconJson { fg = snazzy.yellow },
		DevIconJsx { fg = snazzy.cyan },
		DevIconKotlin { fg = "#f88a02" },
		DevIconKotlinScript { fg = "#f88a02" },
		DevIconKsh { fg = "#4d5a5e" },
		DevIconLeex { fg = "#a074c4" },
		DevIconLess { fg = "#563d7c" },
		DevIconLhs { fg = "#a074c4" },
		DevIconLicense { fg = "#cbcb41" },
		DevIconLock { fg = "#bbbbbb" },
		DevIconLog { fg = "#ffffff" },
		DevIconLua { fg = snazzy.blue },
		DevIconMakefile { fg = "#6d8086" },
		DevIconMarkdown { fg = "#519aba" },
		DevIconMaterial { fg = "#b83998" },
		DevIconMd { fg = "#ffffff" },
		DevIconMdx { fg = "#519aba" },
		DevIconMint { fg = "#87c095" },
		DevIconMixLock { fg = "#a074c4" },
		DevIconMjs { fg = "#f1e05a" },
		DevIconMl { fg = "#e37933" },
		DevIconMli { fg = "#e37933" },
		DevIconMotoko { fg = "#9772fb" },
		DevIconMustache { fg = "#e37933" },
		DevIconNPMIgnore { fg = "#e8274b" },
		DevIconNPMrc { fg = "#e8274b" },
		DevIconNim { fg = "#f3d400" },
		DevIconNix { fg = "#7ebae4" },
		DevIconNodeModules { fg = "#e8274b" },
		DevIconOPUS { fg = "#f88a02" },
		DevIconOpenTypeFont { fg = "#ececec" },
		DevIconPackageJson { fg = "#e8274b" },
		DevIconPackageLockJson { fg = "#7a0d21" },
		DevIconPackedResource { fg = "#6d8086" },
		DevIconPdf { fg = "#b30b00" },
		DevIconPhp { fg = "#a074c4" },
		DevIconPl { fg = "#519aba" },
		DevIconPm { fg = "#519aba" },
		DevIconPng { fg = "#a074c4" },
		DevIconPp { fg = "#ffa61a" },
		DevIconPpt { fg = "#cb4a32" },
		DevIconPrisma { fg = "#ffffff" },
		DevIconProcfile { fg = "#a074c4" },
		DevIconProlog { fg = "#e4b854" },
		DevIconPromptPs1 { fg = "#4d5a5e" },
		DevIconPsb { fg = "#519aba" },
		DevIconPsd { fg = "#519aba" },
		DevIconPy { fg = "#ffbc03" },
		DevIconPyc { fg = "#ffe291" },
		DevIconPyd { fg = "#ffe291" },
		DevIconPyo { fg = "#ffe291" },
		DevIconR { fg = "#358a5b" },
		DevIconRake { fg = snazzy.red },
		DevIconRakeFile { fg = snazzy.red },
		DevIconRb { fg = snazzy.red },
		DevIconRlib { fg = "#dea584" },
		DevIconRmd { fg = "#519aba" },
		DevIconRproj { fg = "#358a5b" },
		DevIconRs { fg = "#dea584" },
		DevIconRss { fg = "#fb9d3b" },
		DevIconSass { fg = "#f55385" },
		DevIconScala { fg = "#cc3e44" },
		DevIconScss { fg = "#f55385" },
		DevIconSettingsJson { fg = "#854cc7" },
		DevIconSh { fg = "#4d5a5e" },
		DevIconSig { fg = "#e37933" },
		DevIconSlim { fg = "#e34c26" },
		DevIconSln { fg = "#854cc7" },
		DevIconSml { fg = "#e37933" },
		DevIconSolidity { fg = "#519aba" },
		DevIconSql { fg = "#dad8d8" },
		DevIconStyl { fg = "#8dc149" },
		DevIconSuo { fg = "#e37933" },
		DevIconSvelte { fg = "#ff3e00" },
		DevIconSvg { fg = "#ffb13b" },
		DevIconSwift { fg = "#e37933" },
		DevIconSystemVerilog { fg = "#019833" },
		DevIconTcl { fg = "#1e5cb3" },
		DevIconTerminal { fg = snazzy.green },
		DevIconTex { fg = "#3d6117" },
		DevIconTextResource { fg = "#cbcb41" },
		DevIconTextScene { fg = "#a074c4" },
		DevIconToml { fg = "#6d8086" },
		DevIconTor { fg = "#519aba" },
		DevIconTs { fg = snazzy.blue },
		DevIconTsx { fg = snazzy.cyan },
		DevIconTwig { fg = "#8dc149" },
		DevIconTxt { fg = "#89e051" },
		DevIconVHDL { fg = "#019833" },
		DevIconVagrantfile { fg = "#1563ff" },
		DevIconVerilog { fg = "#019833" },
		DevIconVim { fg = snazzy.green },
		DevIconVimrc { fg = snazzy.green },
		DevIconVue { fg = "#8dc149" },
		DevIconWebmanifest { fg = "#f1e05a" },
		DevIconWebp { fg = "#a074c4" },
		DevIconWebpack { fg = "#519aba" },
		DevIconXcPlayground { fg = "#e37933" },
		DevIconXls { fg = "#207245" },
		DevIconXml { fg = "#e37933" },
		DevIconXul { fg = "#e37933" },
		DevIconYaml { fg = "#6d8086" },
		DevIconYml { fg = "#6d8086" },
		DevIconZig { fg = "#f69a1b" },
		DevIconZsh { fg = snazzy.green },
		DevIconZshenv { fg = "#89e051" },
		DevIconZshprofile { fg = "#89e051" },
		DevIconZshrc { fg = snazzy.green },
		DiffAdd { fg = snazzy.diff.add },
		DiffChange { fg = snazzy.diff.change },
		DiffDelete { fg = snazzy.diff.delete },
		DiffText { gui = "reverse", fg = snazzy.yellow },
		DiffviewCursorLine { CursorLine },
		DiffviewDiffAddAsDelete { fg = snazzy.diff.delete },
		DiffviewDiffDelete { Comment },
		DiffviewDim1 { fg = "#606580" },
		EndOfBuffer { fg = "#282a36" },
		DiffviewEndOfBuffer { EndOfBuffer },
		DiffviewFilePanelCounter { fg = snazzy.cyan },
		DiffviewFilePanelDeletions { diffRemoved },
		DiffviewFilePanelFileName { fg = "#eff0eb" },
		DiffviewFilePanelInsertions { diffAdded },
		DiffviewFilePanelPath { Comment },
		DiffviewFilePanelTitle { fg = snazzy.yellow },
		DiffviewFilePanelRootPath { DiffviewFilePanelTitle },
		DiffviewNonText { NonText },
		DiffviewNormal { Normal },
		DiffviewPrimary { fg = snazzy.purple },
		DiffviewSecondary { fg = snazzy.yellow },
		DiffviewSignColumn { Normal },
		DiffviewStatusAdded { diffAdded },
		DiffviewStatusBroken { diffRemoved },
		DiffviewStatusCopied { diffChanged },
		DiffviewStatusDeleted { diffRemoved },
		DiffviewStatusIgnored { Comment },
		DiffviewStatusLine { StatusLine },
		DiffviewStatusLineNC { StatusLineNC },
		DiffviewStatusModified { diffChanged },
		DiffviewStatusRenamed { diffChanged },
		DiffviewStatusTypeChange { diffChanged },
		DiffviewStatusUnknown { diffRemoved },
		DiffviewStatusUnmerged { diffChanged },
		DiffviewStatusUntracked { diffAdded },
		Directory { fg = snazzy.cyan },
		DiffviewFolderName { Directory },
		Error { fg = snazzy.red },
		ErrorMsg { fg = snazzy.red },
		Exception { fg = snazzy.red },
		FidgetTask { NonText },
		FidgetTitle { Title },
		Float { fg = "#a1a6a8" },
		FloatBorder { fg = snazzy.cyan },
		FloatShadow { blend = 80, bg = "black" },
		FloatShadowThrough { blend = 100, bg = "black" },
		FloatTitle { FloatBorder },
		FoldColumn { gui = "italic", fg = "#606580" },
		Folded { bg = snazzy.statusline.bg },
		Function { fg = snazzy.purple },
		GitConflictAncestor { bg = "#68217a", gui = "bold" },
		GitConflictAncestorLabel { bg = "#a634c3" },
		GitConflictCurrent { bg = "#434805", gui = "bold" },
		GitConflictCurrentLabel { bg = "#6b7308" },
		GitConflictIncoming { bg = "#00331a", gui = "bold" },
		GitConflictIncomingLabel { bg = "#005129" },
		GitGutterAdd { fg = snazzy.green },
		GitGutterChange { fg = snazzy.yellow },
		GitGutterChangeDelete { fg = snazzy.red },
		GitGutterDelete { fg = snazzy.red },
		GitSignsAdd { fg = snazzy.green },
		GitSignsAddInline { TermCursor },
		GitSignsAddLn { DiffAdd },
		GitSignsAddNr { GitSignsAdd },
		GitSignsAddPreview { DiffAdd },
		GitSignsChange { fg = snazzy.yellow },
		GitSignsChangeInline { TermCursor },
		GitSignsChangeLn { DiffChange },
		GitSignsChangeNr { GitSignsChange },
		GitSignsCurrentLineBlame { fg = "#606580" },
		GitSignsDelete { fg = snazzy.red },
		GitSignsDeleteInline { TermCursor },
		GitSignsDeleteNr { GitSignsDelete },
		GitSignsDeletePreview { DiffDelete },
		GitSignsDeleteVirtLn { DiffDelete },
		HopCursor { Cursor },
		HopNextKey { fg = snazzy.hop.next_key },
		HopNextKey1 { fg = snazzy.hop.next_key1 },
		HopNextKey2 { fg = snazzy.hop.next_key2 },
		HopPreview { fg = "#b8bb26" },
		HopUnmatched { sp = "#666666", fg = "#666666" },
		Ignore { fg = "#686868" },
		IlluminatedWordRead { bg = snazzy.statusline.bg },
		IlluminatedWordText { bg = snazzy.statusline.bg },
		IlluminatedWordWrite { bg = snazzy.statusline.bg },
		InclineNormal { NormalFloat },
		InclineNormalNC { NormalFloat },
		Include { fg = snazzy.yellow },
		IndentBlanklineChar { gui = "nocombine", fg = "#3f444a" },
		IndentBlanklineContextChar { gui = "nocombine", fg = snazzy.yellow },
		IndentBlanklineContextStart { sp = snazzy.yellow, gui = "underline" },
		IndentBlanklineSpaceChar { gui = "nocombine", fg = "#3f444a" },
		IndentBlanklineSpaceCharBlankline { gui = "nocombine", fg = "#3f444a" },
		KeyMenuFloatBorder { fg = snazzy.cyan },
		Keyword { fg = snazzy.magenta },
		Label { fg = snazzy.yellow },
		LeapBackdrop { sp = "#666666", fg = "#666666" },
		LeapLabelPrimary { fg = "#ff007c" },
		LeapLabelSecondary { fg = "#00dfff" },
		FlashBackdrop { sp = "#666666", fg = "#666666" },
		FlashLabel { fg = "#ff007c" },
		-- FlashMatch                                                                                                { fg = "#00dfff" },
		FlashMatch { fg = snazzy.fg },
		FlashCurrent { fg = "#ccff88" },
		LineNr { fg = "#606580" },
		LineNrAbove { LineNr },
		LineNrBelow { LineNr },
		LspComment { gui = "italic", fg = snazzy.ui_8 },
		LspCodeLens { fg = snazzy.ui_8 },
		LspDefaultLibrary { fg = snazzy.yellow },
		LspDefinition { sp = snazzy.statusline.bg, bg = "#3a3d4d", fg = snazzy.blue },
		LspFloatWinBorder { fg = snazzy.cyan },
		LspFunction { fg = snazzy.blue },
		LspInfoBorder { Label },
		LspInfoFiletype { Type },
		LspInfoList { Function },
		LspInfoTip { Comment },
		LspInfoTitle { Title },
		LspInlayHint { fg = snazzy.ui_8 },
		LspInlayHints { fg = snazzy.ui_8 },
		LspKeyword { fg = snazzy.magenta },
		LspMethod { fg = snazzy.blue },
		LspNamespace { gui = "italic", fg = snazzy.blue },
		LspNumber { fg = snazzy.purple },
		LspParameter { fg = snazzy.yellow },
		LspReferenceRead { bg = "#45475a" },
		LspReferenceText { bg = "#45475a" },
		LspReferenceWrite { bg = "#45475a" },
		LspSignatureActiveParameter { bg = "#3a3d4d" },
		LspVariable { fg = "#f1f1f0" },
		MatchBackground { ColorColumn },
		MatchParen { fg = snazzy.yellow },
		MatchParenCur { MatchParen },
		MatchWord { MatchParen },
		ModeMsg { sp = "#192224", fg = "#f9f9f9", bg = "#192224", gui = "bold" },
		MoreMsg { fg = snazzy.yellow },
		MsgSeparator { StatusLine },
		NeotestAdapterName { fg = "#f70067" },
		NeotestDir { fg = "#00f1f5" },
		NeotestExpandMarker { fg = "#8094b4" },
		NeotestFailed { fg = "#f70067" },
		NeotestFile { fg = "#00f1f5" },
		NeotestFocused { gui = "bold,underline" },
		NeotestIndent { fg = "#8b8b8b" },
		NeotestMarked { fg = snazzy.orange },
		NeotestNamespace { fg = "#d484ff" },
		NeotestPassed { fg = snazzy.green },
		NeotestRunning { fg = "#ffec63" },
		NeotestSkipped { fg = "#00f1f5" },
		NeotestTarget { fg = "#f70067" },
		NeotestTest { Normal },
		NeotestUnknown { Normal },
		NeotestWinSelect { fg = "#00f1f5" },
		NotifierContent { Normal },
		NotifierContentDim { Comment },
		NotifierIcon { Title },
		NotifierTitle { Title },
		NotifyBackground { bg = snazzy.bg },
		-- NotifyDEBUGBody                                                                                           { Normal },
		-- NotifyDEBUGBorder                                                                                         { fg=snazzy.cyan, },
		-- NotifyDEBUGIcon                                                                                           { fg=snazzy.cyan, },
		-- NotifyDEBUGTitle                                                                                          { fg=snazzy.cyan, },
		-- NotifyERRORBody                                                                                           { Normal },
		-- NotifyERRORBorder                                                                                         { fg=snazzy.red, },
		-- NotifyERRORIcon                                                                                           { fg=snazzy.magenta, },
		-- NotifyERRORTitle                                                                                          { fg=snazzy.red, },
		-- NotifyINFOBody                                                                                            { Normal },
		-- NotifyINFOBorder                                                                                          { fg=snazzy.green, },
		-- NotifyINFOIcon                                                                                            { fg=snazzy.green, },
		-- NotifyINFOTitle                                                                                           { fg="#eff0eb", },
		-- NotifyLogTime                                                                                             { Comment },
		-- NotifyLogTitle                                                                                            { Special },
		-- NotifyTRACEBody                                                                                           { Normal },
		-- NotifyTRACEBorder                                                                                         { fg=snazzy.purple, },
		-- NotifyTRACEIcon                                                                                           { fg=snazzy.purple, },
		-- NotifyTRACETitle                                                                                          { fg=snazzy.purple, },
		-- NotifyWARNBody                                                                                            { Normal },
		-- NotifyWARNBorder                                                                                          { fg=snazzy.orange, },
		-- NotifyWARNIcon                                                                                            { fg=snazzy.orange, },
		-- NotifyWARNTitle                                                                                           { fg=snazzy.orange, },
		Number { fg = snazzy.yellow },
		NvimArrow { Delimiter },
		NvimAssignment { Operator },
		NvimColon { Delimiter },
		NvimComma { Delimiter },
		NvimFigureBrace { NvimInternalError },
		NvimIdentifier { Identifier },
		NvimInvalid { Error },
		NvimInvalidSingleQuotedUnknownEscape { NvimInternalError },
		NvimInvalidSpacing { ErrorMsg },
		NvimNumber { Number },
		NvimNumberPrefix { Type },
		NvimOperator { Operator },
		NvimOptionSigil { Type },
		NvimParenthesis { Delimiter },
		NvimRegister { SpecialChar },
		NvimSingleQuotedUnknownEscape { NvimInternalError },
		NvimSpacing { Normal },
		NvimString { String },
		NvimStringSpecial { SpecialChar },
		NvimSurroundHighlight { Visual },
		NvimTreeBookmark { fg = snazzy.green },
		NvimTreeCursorColumn { CursorColumn },
		NvimTreeCursorLine { CursorLine },
		NvimTreeEmptyFolderName { Directory },
		NvimTreeEndOfBuffer { EndOfBuffer },
		NvimTreeExecFile { fg = snazzy.green },
		NvimTreeGitDeleted { fg = snazzy.red },
		NvimTreeGitDirty { fg = snazzy.yellow },
		NvimTreeGitMerge { fg = snazzy.yellow },
		NvimTreeGitNew { fg = snazzy.green },
		NvimTreeGitRenamed { fg = snazzy.magenta },
		NvimTreeGitStaged { fg = snazzy.green },
		NvimTreeFileDeleted { NvimTreeGitDeleted },
		NvimTreeFileDirty { NvimTreeGitDirty },
		NvimTreeFileMerge { NvimTreeGitMerge },
		NvimTreeFileNew { NvimTreeGitNew },
		NvimTreeFileRenamed { NvimTreeGitRenamed },
		NvimTreeFileStaged { NvimTreeGitStaged },
		NvimTreeFolderIcon { fg = "#8094b4" },
		NvimTreeFolderName { fg = snazzy.blue },
		NvimTreeGitIgnored { Comment },
		NvimTreeImageFile { fg = snazzy.magenta },
		NvimTreeIndentMarker { fg = "#8094b4" },
		NvimTreeLiveFilterPrefix { fg = snazzy.magenta },
		NvimTreeLiveFilterValue { gui = "bold" },
		NvimTreeLspDiagnosticsError { DiagnosticError },
		NvimTreeLspDiagnosticsHint { DiagnosticHint },
		NvimTreeLspDiagnosticsInformation { DiagnosticInfo },
		NvimTreeLspDiagnosticsWarning { DiagnosticWarn },
		NvimTreeNormal { Normal },
		NvimTreeOpenedFile { fg = snazzy.green },
		NvimTreeOpenedFolderName { Directory },
		NvimTreePopup { Normal },
		NvimTreeRootFolder { fg = snazzy.yellow },
		NvimTreeSpecialFile { fg = "#eff0eb" },
		NvimTreeStatusLine { StatusLine },
		NvimTreeStatusLineNC { StatusLineNC },
		NvimTreeSymlink { fg = snazzy.cyan },
		NvimTreeVertSplit { VertSplit },
		NvimTreeWindowPicker { bg = "#4493c8", fg = "#ededed" },
		DiffviewFolderSign { PreProc },
		Question { fg = snazzy.yellow },
		QuickFixLine { fg = snazzy.magenta },
		RedrawDebugClear { bg = "yellow" },
		RedrawDebugComposed { bg = "green" },
		RedrawDebugNormal { gui = "reverse" },
		RedrawDebugRecompose { bg = snazzy.red, fg = "#f1f1f0" },
		Repeat { fg = snazzy.green },
		STS_highlight { fg = "#00f1f5" },
		ScrollView { Visual },
		SearchSV { fg = snazzy.yellow },
		-- SignColumn                                                                                                { bg = "#282a36" },
		SignColumn { bg = nil },
		SignifySignAdd { fg = snazzy.green },
		SignifySignChange { fg = snazzy.blue },
		SignifySignDelete { fg = snazzy.red },
		SnapBorder { fg = snazzy.blue },
		SnapPosition { fg = snazzy.yellow },
		SnapPrompt { fg = snazzy.magenta },
		SnapSelect { sp = snazzy.statusline.bg, bg = "#3a3d4d" },
		SpellBad { sp = snazzy.red, gui = "underline" },
		SpellCap { gui = "underline", fg = snazzy.blue },
		SpellLocal { gui = "underline", fg = snazzy.cyan },
		SpellRare { gui = "underline", fg = snazzy.magenta },
		TabLine { bg = snazzy.ui_7, gui = "underline" },
		TabLineFill { sp = snazzy.statusline.bg, fg = "#192224", bg = "#3a3d4d", gui = "bold" },
		TabLineSel { sp = "#282a36", fg = "#eff0eb", bg = "#282a36", gui = "bold" },
		Tag { fg = snazzy.yellow },
		TelescopeBorder { fg = snazzy.blue },
		TelescopeMatching { fg = snazzy.green },
		TelescopeMultiIcon { Identifier },
		TelescopeMultiSelection { fg = snazzy.red },
		TelescopeNormal { fg = "#eff0eb" },
		TelescopePreviewBlock { Constant },
		TelescopePreviewBorder { fg = snazzy.blue },
		TelescopePreviewCharDev { Constant },
		TelescopePreviewDate { Directory },
		TelescopePreviewDirectory { Directory },
		TelescopePreviewExecute { String },
		TelescopePreviewGroup { Constant },
		TelescopePreviewHyphen { NonText },
		TelescopePreviewLine { Visual },
		TelescopePreviewLink { Special },
		TelescopePreviewMatch { Search },
		TelescopePreviewNormal { TelescopeNormal },
		TelescopePreviewPipe { Constant },
		TelescopePreviewRead { Constant },
		TelescopePreviewSize { String },
		TelescopePreviewSocket { Statement },
		TelescopePreviewSticky { Keyword },
		TelescopePreviewUser { Constant },
		TelescopePreviewWrite { Statement },
		TelescopePromptBorder { fg = snazzy.blue },
		TelescopePromptCounter { NonText },
		TelescopePromptNormal { TelescopeNormal },
		TelescopePromptPrefix { fg = snazzy.magenta },
		TelescopeResultsBorder { fg = snazzy.blue },
		TelescopeResultsClass { Function },
		TelescopeResultsComment { Comment },
		TelescopeResultsConstant { Constant },
		TelescopeResultsDiffAdd { DiffAdd },
		TelescopeResultsDiffChange { DiffChange },
		TelescopeResultsDiffDelete { DiffDelete },
		TelescopeResultsDiffUntracked { NonText },
		TelescopeResultsField { Function },
		TelescopeResultsFileIcon { Normal },
		TelescopeResultsFunction { Function },
		TelescopeResultsIdentifier { Identifier },
		TelescopeResultsLineNr { LineNr },
		TelescopeResultsNormal { TelescopeNormal },
		TelescopeResultsNumber { Number },
		TelescopeResultsOperator { Operator },
		TelescopeResultsSpecialComment { SpecialComment },
		TelescopeResultsVariable { SpecialChar },
		TelescopeSelection { bg = snazzy.cursorline },
		TelescopeSelectionCaret { fg = snazzy.magenta, bg = snazzy.cursorline },
		TelescopeTitle { TelescopeBorder },
		TodoBgFIX { bg = snazzy.red, fg = "#282a36", gui = "bold" },
		TodoBgHACK { bg = snazzy.yellow, fg = "#282a36", gui = "bold" },
		TodoBgNOTE { bg = snazzy.green, fg = "#282a36", gui = "bold" },
		TodoBgPERF { bg = snazzy.cyan, fg = "#282a36", gui = "bold" },
		TodoBgTODO { bg = snazzy.cyan, fg = "#282a36", gui = "bold" },
		TodoBgWARN { bg = snazzy.yellow, fg = "#282a36", gui = "bold" },
		TodoFgFIX { fg = snazzy.red },
		TodoFgHACK { fg = snazzy.yellow },
		TodoFgNOTE { fg = snazzy.green },
		TodoFgPERF { fg = snazzy.cyan },
		TodoFgTODO { fg = snazzy.cyan },
		TodoFgWARN { fg = snazzy.yellow },
		TodoSignFIX { fg = snazzy.red },
		TodoSignHACK { fg = snazzy.yellow },
		TodoSignNOTE { fg = snazzy.green },
		TodoSignPERF { fg = snazzy.cyan },
		TodoSignTODO { fg = snazzy.cyan },
		TodoSignWARN { bg = "#282a36", fg = snazzy.yellow },
		TreesitterContext { fg = snazzy.fg, bg = snazzy.statusline.bg },
		TreesitterContextLineNumber { fg = snazzy.blue },
		UfoFoldedBg { bg = "#282a36" },
		UfoFoldedEllipsis { Comment },
		UfoFoldedFg { fg = snazzy.blue },
		UfoPreviewSbar { bg = snazzy.blue },
		UfoPreviewThumb { fg = snazzy.blue },
		dbui_tables { fg = snazzy.blue },
		debugBreakpoint { bg = snazzy.red, fg = "#282a36" },
		gitcommitArrow { fg = "#686868" },
		gitcommitDiscarded { fg = "#686868" },
		gitcommitFile { fg = snazzy.green },
		gitcommitOnBranch { fg = "#686868" },
		gitcommitSelected { fg = "#686868" },
		gitcommitSummary { fg = snazzy.red },
		gitcommitUnmerged { fg = "#686868" },
		gitcommitUntracked { fg = "#686868" },
		iCursor { gui = "reverse" },
		lCursor { gui = "reverse" },
		luaBraceError { Error },
		luaComment { Comment },
		luaCond { Conditional },
		luaConstant { Constant },
		luaElse { Conditional },
		luaError { Error },
		luaFor { Repeat },
		luaFunc { Identifier },
		luaFunction { Function },
		luaIn { Operator },
		luaLabel { Label },
		luaNumber { Number },
		luaOperator { Operator },
		luaParenError { Error },
		luaRepeat { Repeat },
		luaSpecial { SpecialChar },
		luaStatement { Statement },
		luaString { String },
		luaString2 { String },
		luaTSConstructor { fg = "#f1f1f0" },
		luaTSPunctBracket { fg = "#f1f1f0" },
		luaTable { Structure },
		luaTodo { Todo },
		vCursor { sp = "#f9f9ff", bg = "#f9f9ff", fg = "#192224" },
		vimCommand { fg = snazzy.blue },
		vimCommentTitle { fg = "#686868" },
		vimFuncName { fg = snazzy.yellow },
		vimFunction { fg = snazzy.magenta },
		vimIsCommand { fg = "#eff0eb" },
		vimLet { fg = snazzy.yellow },
		vimNotFunc { fg = "#686868" },
		vimUserFunc { fg = snazzy.yellow },
		vimVar { fg = snazzy.cyan },
		NavicIconsDefault { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsFile { fg = snazzy.purple, bg = snazzy.statusline.bg },
		NavicIconsFunction { fg = snazzy.magenta, bg = snazzy.statusline.bg },
		NavicIconsMethod { fg = snazzy.magenta, bg = snazzy.statusline.bg },
		NavicText { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicSeparator { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsModule { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsNamespace { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsPackage { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsClass { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsProperty { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsField { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsConstructor { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsEnum { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsInterface { fg = snazzy.fg, bg = snazzy.statusline.bg },
		NavicIconsVariable { NavicIconsDefault },
		NavicIconsConstan { NavicIconsDefault },
		NavicIconsString { NavicIconsDefault },
		NavicIconsNumber { NavicIconsDefault },
		NavicIconsBoolean { NavicIconsDefault },
		NavicIconsArray { NavicIconsDefault },
		NavicIconsObject { NavicIconsDefault },
		NavicIconsKey { NavicIconsDefault },
		NavicIconsNull { NavicIconsDefault },
		NavicIconsEnumMember { NavicIconsDefault },
		NavicIconsStruct { NavicIconsDefault },
		NavicIconsEvent { NavicIconsDefault },
		NavicIconsOperator { NavicIconsDefault },
		NavicIconsTypeParameter { NavicIconsDefault },
		NoiceMini { fg = snazzy.fg, bg = snazzy.bg },
		NoiceLspProgressClient { Title },

		CmpCompletionWindowBorder { fg = snazzy.cyan },
		CmpDocumentationWindowBorder { fg = snazzy.cyan },
		CmpItemAbbrDefault { fg = "#eff0eb" },
		CmpItemAbbr { CmpItemAbbrDefault },
		CmpItemAbbrDeprecatedDefault { fg = "#606580" },
		CmpItemAbbrDeprecated { CmpItemAbbrDeprecatedDefault },
		CmpItemAbbrMatchDefault { fg = "#eff0eb" },
		CmpItemAbbrMatch { fg = snazzy.pink },
		CmpItemAbbrMatchFuzzyDefault { fg = "#eff0eb" },
		CmpItemAbbrMatchFuzzy { fg = snazzy.yellow },
		CmpItemKindDefault { fg = snazzy.yellow },
		CmpItemKind { CmpItemKindDefault },
		CmpItemMenuDefault { fg = "#eff0eb" },
		CmpItemMenu { CmpItemMenuDefault },
		CmpItemKindCodeium { CmpItemKindDefault },

		BlinkCmpDocBorder { fg = snazzy.yellow },
		BlinkCmpDocCursorLine { Visual },
		BlinkCmpDocSeparator { NormalFloat },
		BlinkCmpLabelMatch { CmpItemAbbrMatch },
		-- BlinkCmpMenu { fg = snazzy.fg, bg = snazzy.ui_10 },
		BlinkCmpMenu { fg = snazzy.fg },
		BlinkCmpDoc { BlinkCmpMenu },
		BlinkCmpMenuBorder { fg = snazzy.cyan },
		BlinkCmpMenuSelection { PmenuSel },
		BlinkCmpScrollBarGutter { PmenuSbar },
		BlinkCmpScrollBarThumb { PmenuThumb },
		BlinkCmpSignatureHelp { BlinkCmpMenu },
		BlinkCmpSignatureHelpActiveParameter { LspSignatureActiveParameter },
		BlinkCmpSignatureHelpBorder { NormalFloat },
		BlinkCmpGhostText { fg = snazzy.ui_8 },

		-- blink cmp kind
		-- BlinkCmpKindText              { sym("@markup") },
		BlinkCmpKindText { fg = snazzy.yellow },
		BlinkCmpKindMethod { fg = snazzy.blue },
		BlinkCmpKindFunction { fg = snazzy.blue },
		BlinkCmpKindConstructor { fg = snazzy.blue },
		BlinkCmpKindField { fg = snazzy.cyan },
		BlinkCmpKindVariable { fg = snazzy.base6 },
		BlinkCmpKindClass { fg = snazzy.yellow },
		BlinkCmpKindInterface { fg = snazzy.yellow },
		BlinkCmpKindModule { fg = snazzy.cyan },
		BlinkCmpKindProperty { fg = snazzy.blue },
		BlinkCmpKindUnit { fg = snazzy.purple },
		BlinkCmpKindValue { Normal },
		BlinkCmpKindEnum { Constant },
		BlinkCmpKindKeyword { fg = snazzy.magenta },
		BlinkCmpKindSnippet { Conceal },
		BlinkCmpKindColor { Special },
		BlinkCmpKindFile { Normal },
		BlinkCmpKindReference { gui = "underline" },
		BlinkCmpKindFolder { Directory },
		BlinkCmpKindEnumMember { Constant },
		BlinkCmpKindConstant { Constant },
		BlinkCmpKindStruct { fg = snazzy.yellow },
		BlinkCmpKindEvent { Special },
		BlinkCmpKindOperator { fg = snazzy.orange },
		BlinkCmpKindTypeParameter { Typedef },
		-- Fzf
		FzfLuaDirPart { fg = snazzy.base6 },
		FzfLuaBorder { fg = snazzy.cyan },
		--
		--   Added                                                                                                   { fg="nvimlightgreen", },
		--   Changed                                                                                                 { fg="nvimlightcyan", },
		--   DapUIBreakpointsCurrentLine                                                                             { fg="#a9ff68", gui="bold", },
		--   DapUIBreakpointsDisabledLine                                                                            { fg="#424242", },
		--   DapUIBreakpointsInfo                                                                                    { fg="#a9ff68", },
		--   DapUIBreakpointsLine                                                                                    { DapUILineNumber },
		--   DapUIBreakpointsPath                                                                                    { fg="#00f1f5", },
		--   DapUICurrentFrameName                                                                                   { DapUIBreakpointsCurrentLine },
		--   DapUIDecoration                                                                                         { fg="#00f1f5", },
		--   DapUIEndofBuffer                                                                                        { EndOfBuffer },
		--   DapUIFloatBorder                                                                                        { fg="#00f1f5", },
		--   DapUIFloatNormal                                                                                        { NormalFloat },
		--   DapUIFrameName                                                                                          { Normal },
		--   DapUILineNumber                                                                                         { fg="#00f1f5", },
		--   DapUIModifiedValue                                                                                      { fg="#00f1f5", gui="bold", },
		--   DapUINormal                                                                                             { Normal },
		--   DapUINormalNC                                                                                           { Normal },
		--   DapUIPlayPause                                                                                          { fg="#a9ff68", },
		--   DapUIPlayPauseNC                                                                                        { fg="#a9ff68", },
		--   DapUIRestart                                                                                            { fg="#a9ff68", },
		--   DapUIRestartNC                                                                                          { fg="#a9ff68", },
		--   DapUIScope                                                                                              { fg="#00f1f5", },
		--   DapUISource                                                                                             { fg="#d484ff", },
		--   DapUIStepBack                                                                                           { fg="#00f1f5", },
		--   DapUIStepBackNC                                                                                         { fg="#00f1f5", },
		--   DapUIStepInto                                                                                           { fg="#00f1f5", },
		--   DapUIStepIntoNC                                                                                         { fg="#00f1f5", },
		--   DapUIStepOut                                                                                            { fg="#00f1f5", },
		--   DapUIStepOutNC                                                                                          { fg="#00f1f5", },
		--   DapUIStepOver                                                                                           { fg="#00f1f5", },
		--   DapUIStepOverNC                                                                                         { fg="#00f1f5", },
		--   DapUIStop                                                                                               { fg="#f70067", },
		--   DapUIStopNC                                                                                             { fg="#f70067", },
		--   DapUIStoppedThread                                                                                      { fg="#00f1f5", },
		--   DapUIThread                                                                                             { fg="#a9ff68", },
		--   DapUIType                                                                                               { fg="#d484ff", },
		--   DapUIUnavailable                                                                                        { fg="#424242", },
		--   DapUIUnavailableNC                                                                                      { fg="#424242", },
		--   DapUIValue                                                                                              { Normal },
		--   DapUIVariable                                                                                           { Normal },
		--   DapUIWatchesEmpty                                                                                       { fg="#f70067", },
		--   DapUIWatchesError                                                                                       { fg="#f70067", },
		--   DapUIWatchesValue                                                                                       { fg="#a9ff68", },
		--   DapUIWinSelect                                                                                          { fg="#00f1f5", gui="bold", },
		--   DashboardCenter                                                                                         { fg="#57c7ff", },
		--   DashboardFooter                                                                                         { fg="#686868", },
		--   DashboardHeader                                                                                         { fg="#f3f99f", },
		--   DashboardShortCut                                                                                       { fg="#ff6bc1", },
		--   MarkviewBlockQuoteDefault                                                                               { fg="#606580", },
		--   MarkviewBlockQuoteError                                                                                 { fg="#ff5c57", },
		--   MarkviewBlockQuoteNote                                                                                  { fg="#f3f99f", },
		--   MarkviewBlockQuoteOk                                                                                    { fg="#b3f6c0", },
		--   MarkviewBlockQuoteSpecial                                                                               { fg="#f3f99f", },
		--   MarkviewBlockQuoteWarn                                                                                  { fg="#ff9e42", },
		--   MarkviewCheckboxCancelled                                                                               { fg="#606580", },
		--   MarkviewCheckboxChecked                                                                                 { fg="#b3f6c0", },
		--   MarkviewCheckboxPending                                                                                 { fg="#ff9e42", },
		--   MarkviewCheckboxProgress                                                                                { fg="#f3f99f", },
		--   MarkviewCheckboxStriked                                                                                 { fg="#606580", gui="strikethrough", },
		--   MarkviewCheckboxUnchecked                                                                               { fg="#ff5c57", },
		--   MarkviewCode                                                                                            { bg="#28283d", },
		--   MarkviewCodeInfo                                                                                        { fg="#606580", bg="#28283d", },
		--   MarkviewGradient1                                                                                       { fg="#cdd6f4", },
		--   MarkviewGradient10                                                                                      { fg="#f3f99f", },
		--   MarkviewGradient2                                                                                       { fg="#d1d9ea", },
		--   MarkviewGradient3                                                                                       { fg="#d5dde1", },
		--   MarkviewGradient4                                                                                       { fg="#d9e1d7", },
		--   MarkviewGradient5                                                                                       { fg="#dde5ce", },
		--   MarkviewGradient6                                                                                       { fg="#e2e9c4", },
		--   MarkviewGradient7                                                                                       { fg="#e6edbb", },
		--   MarkviewGradient8                                                                                       { fg="#eaf1b1", },
		--   MarkviewGradient9                                                                                       { fg="#eef5a8", },
		--   MarkviewHeading1                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading1Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewHeading2                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading2Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewHeading3                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading3Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewHeading4                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading4Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewHeading5                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading5Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewHeading6                                                                                        { fg="#f3f99f", bg="#53544a", },
		--   MarkviewHeading6Sign                                                                                    { fg="#f3f99f", },
		--   MarkviewIcon1                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon1Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon1Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewIcon2                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon2Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon2Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewIcon3                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon3Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon3Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewIcon4                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon4Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon4Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewIcon5                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon5Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon5Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewIcon6                                                                                           { fg="#f3f99f", bg="#28283d", },
		--   MarkviewIcon6Fg                                                                                         { fg="#f3f99f", },
		--   MarkviewIcon6Sign                                                                                       { fg="#f3f99f", },
		--   MarkviewInlineCode                                                                                      { bg="#32324c", },
		--   MarkviewLatexSubscript                                                                                  { fg="#a1947b", gui="italic", },
		--   MarkviewLatexSuperscript                                                                                { fg="#6f9473", gui="italic", },
		--   MarkviewListItemMinus                                                                                   { fg="#ff9e42", },
		--   MarkviewListItemPlus                                                                                    { fg="#b3f6c0", },
		--   MarkviewListItemStar                                                                                    { fg="#f3f99f", },
		--   MarkviewTableAlignCenter                                                                                { fg="#add8e6", },
		--   MarkviewTableAlignLeft                                                                                  { fg="#add8e6", },
		--   MarkviewTableAlignRight                                                                                 { fg="#add8e6", },
		--   MarkviewTableBorder                                                                                     { fg="#f3f99f", },
		--   MarkviewTableHeader                                                                                     { fg="#add8e6", },
		--   MatchBackground                                                                                         { ColorColumn },
		--   MatchParen                                                                                              { fg="#59f78e", gui="bold", },
		--   MatchParenCur                                                                                           { MatchParen },
		--   MatchWord                                                                                               { MatchParen },
		--   MiniSurround                                                                                            { IncSearch },
		--   ModeMsg                                                                                                 { fg="#f9f9f9", gui="bold", bg="#192224", sp="#192224", },
		--   MoreMsg                                                                                                 { fg="#f3f99f", gui="bold", },
		--   MsgSeparator                                                                                            { StatusLine },
		--   NoiceCmdlineIcon                                                                                        { DiagnosticSignInfo },
		--   NoiceCmdlineIconSearch                                                                                  { DiagnosticSignWarn },
		--   NoiceCmdlinePopup                                                                                       { Normal },
		--   NoiceCmdlinePopupBorder                                                                                 { DiagnosticSignInfo },
		--   NoiceCmdlinePopupBorderSearch                                                                           { DiagnosticSignWarn },
		--   NoiceCmdlinePopupTitle                                                                                  { DiagnosticSignInfo },
		--   NoiceCmdlinePrompt                                                                                      { Title },
		--   NoiceCompletionItemKindDefault                                                                          { Special },
		--   NoiceConfirm                                                                                            { Normal },
		--   NoiceConfirmBorder                                                                                      { DiagnosticSignInfo },
		--   NoiceCursor                                                                                             { Cursor },
		--   NoiceFormatConfirm                                                                                      { CursorLine },
		--   NoiceFormatConfirmDefault                                                                               { Visual },
		--   NoiceFormatDate                                                                                         { Special },
		--   NoiceFormatEvent                                                                                        { NonText },
		--   NoiceFormatKind                                                                                         { NonText },
		--   NoiceFormatLevelDebug                                                                                   { NonText },
		--   NoiceFormatLevelError                                                                                   { DiagnosticVirtualTextError },
		--   NoiceFormatLevelInfo                                                                                    { DiagnosticVirtualTextInfo },
		--   NoiceFormatLevelOff                                                                                     { NonText },
		--   NoiceFormatLevelTrace                                                                                   { NonText },
		--   NoiceFormatLevelWarn                                                                                    { DiagnosticVirtualTextWarn },
		--   NoiceFormatProgressDone                                                                                 { fg="#eff0eb", bg="#434805", },
		--   NoiceFormatProgressTodo                                                                                 { CursorLine },
		--   NoiceFormatTitle                                                                                        { Title },
		--   NoiceHiddenCursor                                                                                       { gui="nocombine", blend=100, },
		--   NoiceLspProgressClient                                                                                  { Title },
		--   NoiceLspProgressSpinner                                                                                 { Constant },
		--   NoiceLspProgressTitle                                                                                   { NonText },
		--   NoiceMini                                                                                               { fg="#eff0eb", bg="#272935", },
		--   NoicePopup                                                                                              { NormalFloat },
		--   NoicePopupBorder                                                                                        { FloatBorder },
		--   NoicePopupmenu                                                                                          { Pmenu },
		--   NoicePopupmenuBorder                                                                                    { FloatBorder },
		--   NoicePopupmenuMatch                                                                                     { Special },
		--   NoicePopupmenuSelected                                                                                  { PmenuSel },
		--   NoiceScrollbar                                                                                          { PmenuSbar },
		--   NoiceScrollbarThumb                                                                                     { PmenuThumb },
		--   NoiceSplit                                                                                              { NormalFloat },
		--   NoiceSplitBorder                                                                                        { FloatBorder },
		--   NoiceVirtualText                                                                                        { DiagnosticVirtualTextInfo },
		--   NotifierContent                                                                                         { Normal },
		--   NotifierContentDim                                                                                      { Comment },
		--   NotifierIcon                                                                                            { Title },
		--   NotifierTitle                                                                                           { Title },
		--   NotifyBackground                                                                                        { bg="#272935", },
		--   ObsidianBlockID                                                                                         { fg="#89ddff", gui="italic", },
		--   ObsidianBullet                                                                                          { fg="#89ddff", gui="bold", },
		--   ObsidianDone                                                                                            { fg="#89ddff", gui="bold", },
		--   ObsidianExtLinkIcon                                                                                     { fg="#c792ea", },
		--   ObsidianHighlightText                                                                                   { bg="#75662e", },
		--   ObsidianImportant                                                                                       { fg="#d73128", gui="bold", },
		--   ObsidianRefText                                                                                         { fg="#c792ea", gui="underline", },
		--   ObsidianRightArrow                                                                                      { fg="#f78c6c", gui="bold", },
		--   ObsidianTag                                                                                             { fg="#89ddff", gui="italic", },
		--   ObsidianTilde                                                                                           { fg="#ff5370", gui="bold", },
		--   ObsidianTodo                                                                                            { fg="#f78c6c", gui="bold", },
		--   OilChange                                                                                               { Special },
		--   OilCopy                                                                                                 { DiagnosticHint },
		--   OilCreate                                                                                               { DiagnosticInfo },
		--   OilDelete                                                                                               { DiagnosticError },
		--   OilDir                                                                                                  { Directory },
		--   OilHidden                                                                                               { Comment },
		--   OilLinkTarget                                                                                           { Comment },
		--   OilMove                                                                                                 { DiagnosticWarn },
		--   OilOrphanLinkTarget                                                                                     { DiagnosticError },
		--   OilSocket                                                                                               { Keyword },
		--   OilTrashSourcePath                                                                                      { Comment },
		--   Operator                                                                                                { fg="#ff6bc1", gui="bold", },
		--   OtherSelector                                                                                           { Error },
		--   OtherUnderlined                                                                                         { Underlined },
		--   OverseerCANCELED                                                                                        { DiagnosticWarn },
		--   OverseerComponent                                                                                       { Constant },
		--   OverseerDISPOSED                                                                                        { Comment },
		--   OverseerFAILURE                                                                                         { DiagnosticError },
		--   OverseerField                                                                                           { Keyword },
		--   OverseerOutput                                                                                          { Normal },
		--   OverseerPENDING                                                                                         { Normal },
		--   OverseerRUNNING                                                                                         { Constant },
		--   OverseerSUCCESS                                                                                         { DiagnosticOk },
		--   OverseerTask                                                                                            { Title },
		--   OverseerTaskBorder                                                                                      { FloatBorder },
		--   SnacksDashboardDesc                                                                                     { Special },
		--   SnacksDashboardDir                                                                                      { NonText },
		--   SnacksDashboardFile                                                                                     { Special },
		--   SnacksDashboardFooter                                                                                   { Title },
		--   SnacksDashboardHeader                                                                                   { Title },
		--   SnacksDashboardIcon                                                                                     { Special },
		--   SnacksDashboardKey                                                                                      { Number },
		--   SnacksDashboardNormal                                                                                   { Normal },
		--   SnacksDashboardSpecial                                                                                  { Special },
		--   SnacksDashboardTitle                                                                                    { Title },
		--   SnacksIndent                                                                                            { NonText },
		--   SnacksIndent1                                                                                           { DiagnosticInfo },
		--   SnacksIndent2                                                                                           { DiagnosticHint },
		--   SnacksIndent3                                                                                           { DiagnosticWarn },
		--   SnacksIndent4                                                                                           { DiagnosticError },
		--   SnacksIndent5                                                                                           { DiagnosticInfo },
		--   SnacksIndent6                                                                                           { DiagnosticHint },
		--   SnacksIndent7                                                                                           { DiagnosticWarn },
		--   SnacksIndent8                                                                                           { DiagnosticError },
		--   SnacksIndentScope                                                                                       { Special },
		--   SnacksInputBorder                                                                                       { DiagnosticInfo },
		--   SnacksInputIcon                                                                                         { DiagnosticHint },
		--   SnacksInputNormal                                                                                       { Normal },
		--   SnacksInputTitle                                                                                        { DiagnosticInfo },
	}
end)
return theme
